serviceType: LoadBalancer
externalTrafficPolicy: ""

dashboard:
  enabled: true

ssl:
  enabled: true
  enforced: true

  # ref: https://github.com/helm/charts/issues/889#issuecomment-291917890
acme:
  enabled: true
  persistence:
    enabled: false
  staging: true
  # challengeType: tls-alpn-01
  # delayBeforeCheck: 60
  challengeType: dns-01 
  dnsProvider:
    name: digitalocean

# debug: 
#   enabled: true

kubernetes:
  ingressEndpoint:
    useDefaultPublishedService: true

# ref: https://linkerd.io/2/tasks/using-ingress/#traefik
deployment:
  podAnnotations:
    linkerd.io/inject: disabled