## Default values for Traefik
image: traefik
imageTag: 1.7.9

## can switch the service type to NodePort if required
serviceType: LoadBalancer
proxyProtocol:
  enabled: true

ssl:
  enabled: true
  enforced: true
  permanentRedirect: true

acme:
  enabled: true
  email: ${acme_mail}
  onHostRule: true
  staging: true
  logging: false
  # Configure a Let's Encrypt certificate to be managed by default.
  # This is the only way to request wildcard certificates (works only with dns challenge).
  domains:
    enabled: true
    # List of sets of main and (optional) SANs to generate for
    # for wildcard certificates see https://docs.traefik.io/configuration/acme/#wildcard-domains
    domainsList:
      - main: "*.${domain}"
dashboard:
  enabled: true
  domain: traefik.${domain}
